set encoding=utf-8
scriptencoding utf-8

filetype off
filetype plugin indent off

" 先に読ませたい設定の読み込み
if filereadable(expand('~/.vimrc.init'))
	source ~/.vimrc.init
endif

set runtimepath+=~/.vim/
runtime! vimrc.d/init/*.vim
runtime! vimrc.d/dein/*.vim
runtime! vimrc.d/plugins/*.vim

" 環境依存設定の読み込み
if filereadable(expand('~/.vimrc.local'))
	source ~/.vimrc.local
endif

filetype on
filetype plugin indent on

" シンタックスハイライトを有効にする
syntax enable
