# Core
# ------------------------------

[[plugins]]
repo = 'Shougo/vimproc.vim'
if = '! has("nvim") && ! has("win32") && ! has("win64")'
build = 'make'

[[plugins]]
repo = 'Shougo/dein.vim'


# Display
# ------------------------------

# スペースによるインデントを見やすく表示する
[[plugins]]
repo = 'Yggdroot/indentLine'

# 対応する括弧の表示を高速化
[[plugins]]
repo = 'itchyny/vim-cursorword'

# ステータスラインの下に情報を表示する
[[plugins]]
repo = 'Shougo/echodoc.vim'


# Lightline
# ------------------------------

# ステータスライン
[[plugins]]
repo = 'itchyny/lightline.vim'

# ステータスラインのカラーテーマ
[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'


# Unite
# ------------------------------

[[plugins]]
repo = 'Shougo/unite.vim'
if = '! has("nvim") || ! has("python3")'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim") && has("python3")'

# Unite で最近アクセスしたファイルを扱えるようにする
[[plugins]]
repo = 'Shougo/neomru.vim'

# Unite でカラースキーマを変更できるようにする
[[plugins]]
repo = 'ujihisa/unite-colorscheme'

# Unite で Git を扱えるようにする
[[plugins]]
repo = 'kmnk/vim-unite-giti'

# Unite で開いているファイルを保持できるようにする
[[plugins]]
repo = 'Shougo/unite-session'

# Unite でソースのアウトラインを表示する
[[plugins]]
repo = 'Shougo/unite-outline'


# Edit
# ------------------------------

# 単語を囲む要素を扱いやすくする
[[plugins]]
repo = 'tpope/vim-surround'

# Emmet 記法を使えるようにする
[[plugins]]
repo = 'mattn/emmet-vim'

# 閉じ括弧を自動入力
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# `true` と `false` を切り替える
[[plugins]]
repo = 'AndrewRadev/switch.vim'

# コメントイン/アウトの切り替え
[[plugins]]
repo = 'tyru/caw.vim'

# スニペットを扱えるようにする
[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1

# スニペット集
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
depends = 'neosnippet'
on_i = 1

# ペースとしたときにペーストモードにする
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# 表の位置を揃える
[[plugins]]
repo = 'godlygeek/tabular'


# Reference
# ------------------------------

# カーソル下の単語のリファレンスを表示
[[plugins]]
repo = 'thinca/vim-ref'

# 日本語の Vim ドキュメント
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# gf を拡張するためのフレームワーク
[[plugins]]
repo = 'kana/vim-gf-user'

# PHP のクラスを gf で探せるようにする
[[plugins]]
repo = 'violetyk/vim-phpclass'
depends = 'vim-gf-user'
on_ft = [ 'php', 'blade' ]


# Git
# ------------------------------

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'gregsexton/gitv'

[[plugins]]
repo = 'airblade/vim-gitgutter'


# File
# ------------------------------

# `sudo:<ファイル名>` でファイルを開くと root 権限で開く
[[plugins]]
repo = 'vim-scripts/sudo.vim'

# Unite からファイルを扱えるようになる
[[plugins]]
repo = 'Shougo/vimfiler'

# Vimdiff に Git-diff のアルゴリズムを使う
[[plugins]]
repo = 'lambdalisue/vim-unified-diff'


# Syntax
# ------------------------------

# 構文チェック
[[plugins]]
repo = 'vim-syntastic/syntastic'

# 色んな Syntax 詰め合わせ
[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'itkq/fluentd-vim'


# Fixer
# ------------------------------

#[[plugins]]
#repo = 'stephpy/vim-php-cs-fixer'
#on_ft = 'php'
#on_i = 1


# Deoplete / Neocomplete
# ------------------------------

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim") && has("python3")'

[[plugins]]
repo = 'Shougo/neocomplete'
if = '! has("nvim") && has("lua")'

[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-zsh'
if = 'has("nvim") && has("python3")'
depends = 'deoplete.nvim'
on_ft = 'zsh'
on_i = 1

[[plugins]]
repo = 'rafaelndev/deoplete-laravel-plugin'
if = 'has("nvim") && has("python3")'
depends = 'deoplete.nvim'
on_ft = [ 'php', 'blade' ]
on_i = 1

[[plugin]]
repo = 'mhartington/deoplete-typescript'
if = 'has("nvim") && has("python3")'
depends = 'deoplete.nvim'
on_ft = 'typescript'
on_i = 1

[[plugins]]
repo = 'clausreinke/typescript-tools.vim'
if = 'executable("tss")'
on_ft = 'typescript'
on_i = 1


# Colorschema
# ------------------------------

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'sickill/vim-monokai'

[[plugins]]
repo = 'vim-scripts/Wombat'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'junegunn/seoul256.vim'

[[plugins]]
repo = 'morhetz/gruvbox'
