#
# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.
#

# システム全体の設定を読み込む
if [ -f /etc/zshrc ]; then
	source /etc/zshrc
fi

export ZSHHOME="${HOME}/.zsh"

# ヘルパー関数を読み込む
source "${ZSHHOME}/helpers.zsh"


# 先に読ませたい設定を読み込む

local ZSHRC_INIT="${HOME}/.zshrc.init"

if [ -f "${ZSHRC_INIT}" ]; then
	source ${ZSHRC_INIT}
fi


# `zshrc.d` 内のファイルを読み込む

local ZSHRC_DIR="${ZSHHOME}/zshrc.d"

__zshrc_sources "${ZSHRC_DIR}/core"
__zshrc_sources "${ZSHRC_DIR}/plugins.init"
__zshrc_source  "${ZSHRC_DIR}/zplug.zsh"
__zshrc_sources "${ZSHRC_DIR}/services"


# 環境ごとの設定を読み込む

local ZSHRC_LOCAL="${HOME}/.zshrc.local"

if [ -f "${ZSHRC_LOCAL}" ]; then
	source ${ZSHRC_LOCAL}
fi


#
# `zshrc.local` での設定例
#

# ブランチ名の表示を無効化
#export CURRENT_BRANCH_DISABLED=1

# ブランチ名の表示色を固定化
#export CURRENT_BRANCH_COLOR_DISABLED=1
