# システム全体の設定を読み込む
__helpers::source "/etc/zshrc"

# 先に読ませたい設定を読み込む
__helpers::source "${HOME}/.zshrc.init"


# `conf.d` 内のファイルを読み込む

local ZSHRC_DIR="${ZSH_HOME}/conf.d"

__helpers::sources "${ZSHRC_DIR}/core"
__helpers::sources "${ZSHRC_DIR}/plugins"
__helpers::source  "${ZSHRC_DIR}/zplug.zsh"
__helpers::sources "${ZSHRC_DIR}/functions"
__helpers::sources "${ZSHRC_DIR}/services"
__helpers::sources "${ZSHRC_DIR}/aliases"


# 環境ごとの設定を読み込む
__helpers::source "${HOME}/.zshrc.local"
