#
# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.
#

# Source global definitions
if [ -f /etc/zshrc ]; then
	source /etc/zshrc
fi

export ZSHHOME="${HOME}/.zsh"

# ヘルパー関数を読み込む
source "$ZSHHOME/helpers.zsh"


# `zshrc.d` 内のファイルを読み込む

local ZSHRC_DIR="${ZSHHOME}/zshrc.d"

__zshrc_sources "$ZSHRC_DIR/core"
__zshrc_source  "$ZSHRC_DIR/zplug.zsh"
__zshrc_sources "$ZSHRC_DIR/services"


# 環境ごとの設定を読み込む

local ZSHRC_LOCAL="${HOME}/.zshrc.local"

if [ -f $ZSHRC_LOCAL ]; then
	source $ZSHRC_LOCAL
fi


# ブランチ名の表示を無効にする
#export CURRENT_BRANCH_DISABLED=1
